name: Deploy to AWS

on:
  push:
    branches:
      - main  # Ejecutar el flujo cuando haya commits en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TERRAFORM_VERSION: 1.9.7

    steps:
      # Checkout del repositorio
      - name: Check out code
        uses: actions/checkout@v2

      # Instalar Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ajusta la versión de Node.js si es necesario

      # Instalar JSDoc
      - name: Install JSDoc
        run: npm install -g jsdoc  # Instala JSDoc globalmentee

      # Generar la documentación con JSDoc
      - name: Generate JSDoc documentation
        run: jsdoc Web/js/index.js -d Web/docs  # Genera la documentación en Web/docs

      # Configurar las credenciales de AWS
      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      # Iniciar Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Cambia esto a solo "terraform"

      # Aplicar cambios con Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        working-directory: terraform  # Cambia esto a solo "terraform"
